name: CI with Codon
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl

      - name: Install Codon
        run: |
          mkdir -p ${HOME}/.codon
          curl -L https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz | tar zxvf - --strip-components=1 -C ${HOME}/.codon
          curl -L https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux-x86_64.tar.gz | tar zxvf - -C ${HOME}/.codon/lib/codon/plugins
          echo "$HOME/.codon/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          pip install find_libpython

      - name: Set up Codon Python bridge
        run: |
          CODON_PYTHON=$(python -c "import find_libpython; print(find_libpython.find_libpython())")
          echo "CODON_PYTHON=$CODON_PYTHON" >> $GITHUB_ENV
          echo "Found Python library at: ${CODON_PYTHON}"

      - name: Verify installations
        run: |
          which codon
          codon --version
          python --version
          echo "Python library path: $CODON_PYTHON"

      - name: Run basic tests
        run: |
          # Add your actual test commands here
          echo "Running tests..."
          # Example: codon run your_script.codon
